name: Daily Deny Check

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  deny:
    name: Run cargo deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: Advisory Cache
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809
        with:
          path: ~/.cargo/advisory-db
          key: rust-advisory-db

      - name: Install cargo deny
        run: cargo +1.91.1 install cargo-deny --version =0.18.6

      - name: Run cargo deny
        run: cargo deny -L error --all-features check --hide-inclusion-graph
