name: Monero Tests

on:
  push:
    branches:
      - main
    paths:
      - "monero-oxide/**"

  pull_request:
    paths:
      - "monero-oxide/**"

  workflow_dispatch:

jobs:
  # Only run these once since they will be consistent regardless of any node
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: Test Dependencies
        uses: ./.github/actions/test-dependencies

      - name: Run Unit Tests With and Without `--all-features`
        run: |
          function check_workspace {
            # Get the members array from the workspace's `Cargo.toml`
            cargo_toml_lines=$(cat ./Cargo.toml | wc -l)
            members=$(cat Cargo.toml | grep "members\ \=\ \[" -m1 -A$cargo_toml_lines | grep "]" -m1 -B$cargo_toml_lines)
            # Prune `members = [` to `[` by replacing the first line with just `[`
            members=$(echo "$members" | sed "1s/.*/\[/")
            # Remove the trailing comma by replacing the last line's "," with ""
            members=$(echo "$members" | sed "$(($(echo "$members" | wc -l) - 1))s/\,//")

            echo $members | jq -r ".[]" | while read -r member; do
              echo Testing $member

              GITHUB_CI=true RUST_BACKTRACE=1 cargo test --manifest-path $member/Cargo.toml --lib
              correct=$?
              if [ $correct -ne 0 ]; then
                return $correct
              fi

              GITHUB_CI=true RUST_BACKTRACE=1 cargo test --manifest-path $member/Cargo.toml --lib --all-features
              correct=$?
              if [ $correct -ne 0 ]; then
                return $correct
              fi
            done
          }
          check_workspace

  integration-tests:
    runs-on: ubuntu-latest
    # Test against all supported protocol versions
    strategy:
      matrix:
        version: [v0.17.3.2, v0.18.4.4]

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: Test Dependencies
        uses: ./.github/actions/test-dependencies
        with:
          monero-version: ${{ matrix.version }}

      - name: Run Integration Tests
        run: |
          # GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-oxide --test '*'

      - name: Run Integration Tests With All Features
        run: |
          # GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-oxide --all-features --test '*'
